name:                kaleidoscope
version:             0.1.0.0
github:              "sudo-rushil/kaleidoscope"
license:             MIT
author:              "Rushil Mallarapu"
maintainer:          "rushil.mallarapu@gmail.com"
copyright:           "Rushil Mallarapu"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/sudo-rushil/kaleidoscope#readme>

dependencies:
- base >= 4.7 && < 5
- haskeline >= 0.7.1
- llvm-hs >= 9.0
- llvm-hs-pure >= 9.0
- parsec >= 3.1
- containers >= 0.4
- mtl >= 2.2
- bytestring >= 0.10
- transformers >= 0.3 && < 0.6

library:
  source-dirs:
    - src
  c-sources:
    src/cbits.c

executables:
  kaleidoscope:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kaleidoscope
